### ISSUE TITLE
BUG: API errors out without certain values

### ISSUE THREAD

**Issue by 87maza** [chummer80/soup-du-jour#21]
need to write if statement for:

<%= @meetupapi['results'][0]['name']%>
<%=@meetupapi['results'][0]['description'].html_safe %><br>
<%=link_to "Go to MeetUp Page", @meetupapi['results'][0]['event_url']%>

if no value for [name], exclude value

**Comment by chummer80** [comment]
Instead of using if statements, using 'rescue' might be easier.  Example:

begin
  meetup_name = @meetupapi['results'][0]['name']    # this statement has a chance of causing errors
rescue
  meetup_name = ""    # this is the backup plan
end
